### ISSUE TITLE
Double playback with plugins disabled

### ISSUE THREAD

**Issue by greneholt** [greneholt/youtube5#39]
YouTube has now enabled HTML5 playback even when you are not in the beta.

**Comment by greneholt** [comment]
I can't reproduce this issue consistently, which makes it difficult to debug. If there are any particular videos you have seen it occur on, please link to them.

**Comment by dlh** [comment]
Here's [one example](http://www.youtube.com/watch?v=TStkvLmHkoY) (not sure how I stumbled upon that… but at least it loads quickly and exhibits the issue).

Blocking the `/https?:\/\/s\.ytimg\.com\/yts\/jsbin\/html5player-.+\.js/` script from loading works, but it breaks the `Use original player` feature for users that have plugins disabled. That's not an issue for me because YouTube's HTML5 player generally doesn't work—it will play the audio track but show no video. For users that have plugins enabled the `Use original player` feature still works.

**Comment by greneholt** [comment]
That example doesn't trigger it for me. I did experience it once on another video, but it's stopped occurring now.

The "Use original player" feature never really worked if you have plugins disabled, so that's no big loss.

**Comment by dlh** [comment]
You can turn off plugins and the YouTube5 extension to easily find videos with this issue. If it loads the YouTube HTML5 player, then it will have the double playback issue when YouTube5 is enabled.

It seems to only be videos with monetization (ads) off, since YouTube won't load their HTML5 player for those videos and instead asks you to install Flash.

Here's [another video](http://www.youtube.com/watch?v=156IkZWqIac&list=TLkuSXsw-SwPg).

**Comment by greneholt** [comment]
Fixed in v2.6.4
